[build]
builder = "nixpacks"
providers = ["php", "node"]
installCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm ci"
buildCommand = "php artisan config:clear && php artisan cache:clear && bash start.sh"

[deploy]
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments]
  [environments.production]
  envs = [
    "APP_NAME=Space",
    "APP_ENV=production",
    "APP_DEBUG=false",
    "LOG_LEVEL=error"
  ]

[nixpacks]
# Optional: Explicitly set versions if needed, otherwise Nixpacks uses defaults or detects from files like composer.json
# phpVersion = "8.2"
# nodeVersion = "18" # Or your required Node version 