[build]
builder = "nixpacks"
providers = ["php", "node"]
installCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && npm ci"
buildCommand = "php artisan config:clear && npm run build"

[deploy]
startCommand = "php artisan migrate --force || true; php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 90
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments]
  [environments.production]
  envs = [
    "APP_NAME=Space",
    "APP_ENV=production",
    "APP_DEBUG=true",
    "LOG_LEVEL=debug"
  ]

[nixpacks]
# Optional: Explicitly set versions if needed, otherwise Nixpacks uses defaults or detects from files like composer.json
# phpVersion = "8.2"
# nodeVersion = "18" # Or your required Node version 