[build]
builder = "nixpacks"
buildCommand = "composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev && php artisan config:clear && php artisan migrate --force && npm ci && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments]
  [environments.production]
  envs = [
    "APP_NAME=Space",
    "APP_ENV=production",
    "APP_DEBUG=false",
    "LOG_LEVEL=error"
  ] 